export const COUNTRIES = [
    "Portugal",
    "Espanha",
    "França",
    "Reino Unido",
    "Alemanha",
    "Itália",
    "Países Baixos",
    "Bélgica",
    "Suíça",
    "Áustria",
    "Irlanda",
    "Dinamarca",
    "Suécia",
    "Noruega",
    "Finlândia",
    "Polónia",
    "República Checa",
    "Hungria",
    "Grécia",
    "Brasil",
    "Estados Unidos",
    "Canadá",
    "Angola",
    "Moçambique",
    "Cabo Verde",
    "Guiné-Bissau",
    "São Tomé e Príncipe",
    "Timor-Leste",
    "Outro"
].sort((a, b) => a === "Portugal" ? -1 : b === "Portugal" ? 1 : a.localeCompare(b));
